"""Updated models

Revision ID: 40913316ad9d
Revises: 
Create Date: 2025-03-27 02:01:30.082770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '40913316ad9d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('challenge_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('EventType', sa.Enum('TRANSCRIPTION_CHALLENGE', 'TRANSLATION_SPRINT', 'CORRECTION_MARATHON', name='eventtype'), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('target_contribution_count', sa.Integer(), nullable=True),
    sa.Column('participant_count', sa.Integer(), nullable=False),
    sa.Column('contribution_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_id'), 'challenge', ['id'], unique=False)
    op.create_table('language',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contribution_count', sa.Integer(), nullable=False),
    sa.Column('contributor_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_language_code'), 'language', ['code'], unique=True)
    op.create_index(op.f('ix_language_id'), 'language', ['id'], unique=False)
    op.create_table('modelmetadata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dataset_used', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modelmetadata_id'), 'modelmetadata', ['id'], unique=False)
    op.create_table('translation_seed_data',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('original_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_seed_data_id'), 'translation_seed_data', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('recently_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('contribution_count', sa.Integer(), nullable=False),
    sa.Column('accepted_contributions', sa.Integer(), nullable=False),
    sa.Column('reputation_score', sa.Float(), nullable=False),
    sa.Column('total_hours_speech', sa.Integer(), nullable=False),
    sa.Column('total_sentences_translated', sa.Integer(), nullable=False),
    sa.Column('total_tokens_produced', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('challengeparticipation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('total_hours_speech', sa.Integer(), nullable=False),
    sa.Column('total_sentences_translated', sa.Integer(), nullable=False),
    sa.Column('total_tokens_produced', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('acceptance_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['challenge.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challengeparticipation_id'), 'challengeparticipation', ['id'], unique=False)
    op.create_table('storage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_id'), 'storage', ['id'], unique=False)
    op.create_table('transcription_sample',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('language_id', sa.Uuid(), nullable=False),
    sa.Column('audio_urls', sa.JSON(), nullable=True),
    sa.Column('transcription_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sm1', sa.Integer(), nullable=False),
    sa.Column('sm2', sa.Integer(), nullable=False),
    sa.Column('sm3', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcription_sample_id'), 'transcription_sample', ['id'], unique=False)
    op.create_table('translation_sample',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seed_data_id', sa.Uuid(), nullable=False),
    sa.Column('language_id', sa.Uuid(), nullable=False),
    sa.Column('translated_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sm1', sa.Integer(), nullable=False),
    sa.Column('sm2', sa.Integer(), nullable=False),
    sa.Column('sm3', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['seed_data_id'], ['translation_seed_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_sample_id'), 'translation_sample', ['id'], unique=False)
    op.create_table('user_language',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('language_id', sa.Uuid(), nullable=False),
    sa.Column('total_hours_speech', sa.Integer(), nullable=True),
    sa.Column('total_sentences_translated', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_language_id'), 'user_language', ['id'], unique=False)
    op.create_table('transcription_contribution',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('transcription_sample_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['transcription_sample_id'], ['transcription_sample.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcription_contribution_id'), 'transcription_contribution', ['id'], unique=False)
    op.create_table('translation_contribution',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('translation_sample_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['translation_sample_id'], ['translation_sample.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_contribution_id'), 'translation_contribution', ['id'], unique=False)
    op.create_table('transcriptioncirculationrecord',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transcription_contribution_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('shown_at', sa.DateTime(), nullable=False),
    sa.Column('voted', sa.Boolean(), nullable=False),
    sa.Column('skipped', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['transcription_contribution_id'], ['transcription_contribution.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcriptioncirculationrecord_id'), 'transcriptioncirculationrecord', ['id'], unique=False)
    op.create_table('translationcirculationrecord',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('translation_contribution_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('shown_at', sa.DateTime(), nullable=False),
    sa.Column('voted', sa.Boolean(), nullable=False),
    sa.Column('skipped', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['translation_contribution_id'], ['translation_contribution.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translationcirculationrecord_id'), 'translationcirculationrecord', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translationcirculationrecord_id'), table_name='translationcirculationrecord')
    op.drop_table('translationcirculationrecord')
    op.drop_index(op.f('ix_transcriptioncirculationrecord_id'), table_name='transcriptioncirculationrecord')
    op.drop_table('transcriptioncirculationrecord')
    op.drop_index(op.f('ix_translation_contribution_id'), table_name='translation_contribution')
    op.drop_table('translation_contribution')
    op.drop_index(op.f('ix_transcription_contribution_id'), table_name='transcription_contribution')
    op.drop_table('transcription_contribution')
    op.drop_index(op.f('ix_user_language_id'), table_name='user_language')
    op.drop_table('user_language')
    op.drop_index(op.f('ix_translation_sample_id'), table_name='translation_sample')
    op.drop_table('translation_sample')
    op.drop_index(op.f('ix_transcription_sample_id'), table_name='transcription_sample')
    op.drop_table('transcription_sample')
    op.drop_index(op.f('ix_storage_id'), table_name='storage')
    op.drop_table('storage')
    op.drop_index(op.f('ix_challengeparticipation_id'), table_name='challengeparticipation')
    op.drop_table('challengeparticipation')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_translation_seed_data_id'), table_name='translation_seed_data')
    op.drop_table('translation_seed_data')
    op.drop_index(op.f('ix_modelmetadata_id'), table_name='modelmetadata')
    op.drop_table('modelmetadata')
    op.drop_index(op.f('ix_language_id'), table_name='language')
    op.drop_index(op.f('ix_language_code'), table_name='language')
    op.drop_table('language')
    op.drop_index(op.f('ix_challenge_id'), table_name='challenge')
    op.drop_table('challenge')
    # ### end Alembic commands ###
