"""ancestor list passed to instance obj

Revision ID: 06b6338e26e4
Revises: 8b98de09fae5
Create Date: 2025-07-06 17:07:10.125406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06b6338e26e4'
down_revision: Union[str, None] = '8b98de09fae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotation_sample', 'ancestors')
    op.add_column('evaluation_instance', sa.Column('ancestors', sa.JSON(), nullable=True))
    op.drop_column('transcription_sample', 'ancestors')
    op.drop_column('translation_sample', 'ancestors')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translation_sample', sa.Column('ancestors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('transcription_sample', sa.Column('ancestors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('evaluation_instance', 'ancestors')
    op.add_column('annotation_sample', sa.Column('ancestors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
