"""sample ancestor list update

Revision ID: 8b98de09fae5
Revises: 6efabef018aa
Create Date: 2025-07-04 20:27:21.929398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8b98de09fae5'
down_revision: Union[str, None] = '6efabef018aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation_sample', sa.Column('ancestors', sa.JSON(), nullable=True))
    op.add_column('transcription_sample', sa.Column('ancestors', sa.JSON(), nullable=True))
    op.add_column('translation_sample', sa.Column('ancestors', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translation_sample', 'ancestors')
    op.drop_column('transcription_sample', 'ancestors')
    op.drop_column('annotation_sample', 'ancestors')
    # ### end Alembic commands ###
