"""Bantu DBv2

Revision ID: d0f6534712ff
Revises: 
Create Date: 2025-04-06 23:05:43.503340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd0f6534712ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation_seed_data',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('annotation_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_seed_data_id'), 'annotation_seed_data', ['id'], unique=False)
    op.create_table('challenge',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('challenge_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('event_type', sa.Enum('DATA_COLLECTION', 'SAMPLE_REVIEW', name='eventtype'), nullable=False),
    sa.Column('task_type', sa.Enum('TRANSCRIPTION', 'TRANSLATION', 'ANNOTATION', name='tasktype'), nullable=False),
    sa.Column('event_category', sa.Enum('COMPETITION', 'BOUNTY', name='eventcategory'), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('UPCOMING', 'ACTIVE', 'COMPLETED', name='challengestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('participant_count', sa.Integer(), nullable=False),
    sa.Column('contribution_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_id'), 'challenge', ['id'], unique=False)
    op.create_table('language',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contribution_count', sa.Integer(), nullable=False),
    sa.Column('contributor_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_language_code'), 'language', ['code'], unique=True)
    op.create_index(op.f('ix_language_id'), 'language', ['id'], unique=False)
    op.create_table('milestone',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reward_type', sa.Enum('CASH', 'BADGE', 'RANK', name='rewardtype'), nullable=False),
    sa.Column('reward_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('required_actions', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milestone_id'), 'milestone', ['id'], unique=False)
    op.create_table('model_metadata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dataset_used', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_metadata_id'), 'model_metadata', ['id'], unique=False)
    op.create_table('translation_seed_data',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('original_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_seed_data_id'), 'translation_seed_data', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fullname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('recently_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_country'), 'user', ['country'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_fullname'), 'user', ['fullname'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('annotation_sample',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seed_data_id', sa.Uuid(), nullable=False),
    sa.Column('language_id', sa.Uuid(), nullable=False),
    sa.Column('annotation_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['seed_data_id'], ['annotation_seed_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_sample_id'), 'annotation_sample', ['id'], unique=False)
    op.create_table('challenge_participation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('total_hours_speech', sa.Integer(), nullable=False),
    sa.Column('total_sentences_translated', sa.Integer(), nullable=False),
    sa.Column('total_tokens_produced', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('acceptance_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['challenge.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_participation_id'), 'challenge_participation', ['id'], unique=False)
    op.create_table('challenge_reward',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('challenge_id', sa.Uuid(), nullable=False),
    sa.Column('reward_type', sa.Enum('CASH', 'BADGE', 'RANK', name='rewardtype'), nullable=False),
    sa.Column('reward_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('claimed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_reward_id'), 'challenge_reward', ['id'], unique=False)
    op.create_table('refresh_token',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('device_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('rotations_count', sa.Integer(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_token_id'), 'refresh_token', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_token_token_hash'), 'refresh_token', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_token_user_id'), 'refresh_token', ['user_id'], unique=False)
    op.create_table('transcription_sample',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('language_id', sa.Uuid(), nullable=False),
    sa.Column('audio_urls', sa.JSON(), nullable=True),
    sa.Column('transcription_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sm1', sa.Integer(), nullable=False),
    sa.Column('sm2', sa.Integer(), nullable=False),
    sa.Column('sm3', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcription_sample_id'), 'transcription_sample', ['id'], unique=False)
    op.create_table('translation_sample',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seed_data_id', sa.Uuid(), nullable=False),
    sa.Column('language_id', sa.Uuid(), nullable=False),
    sa.Column('translated_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sm1', sa.Integer(), nullable=False),
    sa.Column('sm2', sa.Integer(), nullable=False),
    sa.Column('sm3', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['seed_data_id'], ['translation_seed_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_sample_id'), 'translation_sample', ['id'], unique=False)
    op.create_table('user_language',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('language_id', sa.Uuid(), nullable=False),
    sa.Column('proficiency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_hours_speech', sa.Integer(), nullable=False),
    sa.Column('total_sentences_translated', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_language_id'), 'user_language', ['id'], unique=False)
    op.create_table('user_milestone',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('milestone_id', sa.Uuid(), nullable=False),
    sa.Column('achieved_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestone.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_milestone_id'), 'user_milestone', ['id'], unique=False)
    op.create_table('userstatistics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('translation_contribution_count', sa.Integer(), nullable=False),
    sa.Column('translation_accepted_contributions', sa.Integer(), nullable=False),
    sa.Column('translation_reputation_score', sa.Float(), nullable=False),
    sa.Column('transcription_contribution_count', sa.Integer(), nullable=False),
    sa.Column('transcription_accepted_contributions', sa.Integer(), nullable=False),
    sa.Column('transcription_reputation_score', sa.Float(), nullable=False),
    sa.Column('total_hours_speech', sa.Integer(), nullable=False),
    sa.Column('total_sentences_translated', sa.Integer(), nullable=False),
    sa.Column('total_tokens_produced', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_userstatistics_id'), 'userstatistics', ['id'], unique=False)
    op.create_table('annotation_contribution',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('annotation_sample_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['annotation_sample_id'], ['annotation_sample.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_contribution_id'), 'annotation_contribution', ['id'], unique=False)
    op.create_table('reward_distribution',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reward_id', sa.Uuid(), nullable=False),
    sa.Column('distribution_type', sa.Enum('FIXED', 'PERCENTAGE', 'TIERED', name='rewarddistributiontype'), nullable=False),
    sa.Column('allocation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['reward_id'], ['challenge_reward.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reward_distribution_id'), 'reward_distribution', ['id'], unique=False)
    op.create_table('transcription_contribution',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('transcription_sample_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['transcription_sample_id'], ['transcription_sample.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcription_contribution_id'), 'transcription_contribution', ['id'], unique=False)
    op.create_table('translation_contribution',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('translation_sample_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['translation_sample_id'], ['translation_sample.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_contribution_id'), 'translation_contribution', ['id'], unique=False)
    op.create_table('user_challenge_reward',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('reward_id', sa.Uuid(), nullable=False),
    sa.Column('awarded_at', sa.DateTime(), nullable=False),
    sa.Column('claimed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['reward_id'], ['challenge_reward.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_challenge_reward_id'), 'user_challenge_reward', ['id'], unique=False)
    op.create_table('annotation_circulation_record',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('annotation_contribution_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('shown_at', sa.DateTime(), nullable=False),
    sa.Column('voted', sa.Boolean(), nullable=False),
    sa.Column('skipped', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['annotation_contribution_id'], ['annotation_contribution.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_circulation_record_id'), 'annotation_circulation_record', ['id'], unique=False)
    op.create_table('transcription_circulation_record',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transcription_contribution_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('shown_at', sa.DateTime(), nullable=False),
    sa.Column('voted', sa.Boolean(), nullable=False),
    sa.Column('skipped', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['transcription_contribution_id'], ['transcription_contribution.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcription_circulation_record_id'), 'transcription_circulation_record', ['id'], unique=False)
    op.create_table('translation_circulation_record',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('translation_contribution_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('shown_at', sa.DateTime(), nullable=False),
    sa.Column('voted', sa.Boolean(), nullable=False),
    sa.Column('skipped', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['translation_contribution_id'], ['translation_contribution.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_circulation_record_id'), 'translation_circulation_record', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translation_circulation_record_id'), table_name='translation_circulation_record')
    op.drop_table('translation_circulation_record')
    op.drop_index(op.f('ix_transcription_circulation_record_id'), table_name='transcription_circulation_record')
    op.drop_table('transcription_circulation_record')
    op.drop_index(op.f('ix_annotation_circulation_record_id'), table_name='annotation_circulation_record')
    op.drop_table('annotation_circulation_record')
    op.drop_index(op.f('ix_user_challenge_reward_id'), table_name='user_challenge_reward')
    op.drop_table('user_challenge_reward')
    op.drop_index(op.f('ix_translation_contribution_id'), table_name='translation_contribution')
    op.drop_table('translation_contribution')
    op.drop_index(op.f('ix_transcription_contribution_id'), table_name='transcription_contribution')
    op.drop_table('transcription_contribution')
    op.drop_index(op.f('ix_reward_distribution_id'), table_name='reward_distribution')
    op.drop_table('reward_distribution')
    op.drop_index(op.f('ix_annotation_contribution_id'), table_name='annotation_contribution')
    op.drop_table('annotation_contribution')
    op.drop_index(op.f('ix_userstatistics_id'), table_name='userstatistics')
    op.drop_table('userstatistics')
    op.drop_index(op.f('ix_user_milestone_id'), table_name='user_milestone')
    op.drop_table('user_milestone')
    op.drop_index(op.f('ix_user_language_id'), table_name='user_language')
    op.drop_table('user_language')
    op.drop_index(op.f('ix_translation_sample_id'), table_name='translation_sample')
    op.drop_table('translation_sample')
    op.drop_index(op.f('ix_transcription_sample_id'), table_name='transcription_sample')
    op.drop_table('transcription_sample')
    op.drop_index(op.f('ix_refresh_token_user_id'), table_name='refresh_token')
    op.drop_index(op.f('ix_refresh_token_token_hash'), table_name='refresh_token')
    op.drop_index(op.f('ix_refresh_token_id'), table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_index(op.f('ix_challenge_reward_id'), table_name='challenge_reward')
    op.drop_table('challenge_reward')
    op.drop_index(op.f('ix_challenge_participation_id'), table_name='challenge_participation')
    op.drop_table('challenge_participation')
    op.drop_index(op.f('ix_annotation_sample_id'), table_name='annotation_sample')
    op.drop_table('annotation_sample')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_fullname'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_country'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_translation_seed_data_id'), table_name='translation_seed_data')
    op.drop_table('translation_seed_data')
    op.drop_index(op.f('ix_model_metadata_id'), table_name='model_metadata')
    op.drop_table('model_metadata')
    op.drop_index(op.f('ix_milestone_id'), table_name='milestone')
    op.drop_table('milestone')
    op.drop_index(op.f('ix_language_id'), table_name='language')
    op.drop_index(op.f('ix_language_code'), table_name='language')
    op.drop_table('language')
    op.drop_index(op.f('ix_challenge_id'), table_name='challenge')
    op.drop_table('challenge')
    op.drop_index(op.f('ix_annotation_seed_data_id'), table_name='annotation_seed_data')
    op.drop_table('annotation_seed_data')
    # ### end Alembic commands ###
